// musemesh - UI strings (en / sr Cyrillic). UTF-8 ON PURPOSE - the ONE site
// file allowed non-ASCII. EDIT ONLY IN A CODE EDITOR (VS Code etc.), NEVER
// TextEdit: TextEdit re-saves rendered soup and destroyed this site once.
// Keys/values are normative from spec 6 of
// docs/superpowers/specs/2026-07-16-musemesh-free-for-now-design.md
var MUSEMESH_STRINGS = {
  en: {
    'titlebar': '❯ include the audience',
    'wordmark': 'musemesh',
    'menu.home': 'HOME',
    'menu.how': 'HOW IT WORKS',
    'menu.run': 'RUN A ROOM',
    'menu.about': 'ABOUT',
    'menu.contact': 'CONTACT',
    'home.tagline': 'every phone in the room becomes a speaker',
    'home.line': "no app. scan a QR code, tap once — you're part of the sound system.",
    'home.cta': '[ how it works ]',
    'how.h': 'HOW IT WORKS',
    'how.1': '> a performer hosts a room — a tiny server in their DAW or app',
    'how.wifi': "> everyone joins the venue's wifi — performer and phones on the same network",
    'how.2': '> the crowd scans a QR code. no app, no signup — the browser is the speaker',
    'how.3': '> every phone plays its own channel, in sync',
    'how.4': '> the room becomes the sound system',
    'how.lights': '> coming soon: the room becomes the light show too — every phone a synced stage light, played from MIDI clips',
    'run.h': 'RUN A ROOM',
    'run.1': '> load musemesh-server in your DAW (VST3/AU)',
    'run.2': '> send it channels with musemesh-channel',
    'run.3': '> show the QR — the crowd does the rest',
    'run.lights': '> coming soon: musemesh-light — phones as synced stage lights',
    'run.dl': '[ download — free ]',
    'run.dlnote': 'macOS VST3/AU · ~30 MB · unsigned build — see INSTALL.txt inside',
    'about.h': 'ABOUT',
    'about.text': "musemesh is an experiment in shared performance: instead of one PA, the audience's phones become a distributed speaker orchestra. first born five years ago, it was presented at ITP Camp 2021 with great success. built by relja petrovic + ai.",
    'contact.h': 'CONTACT',
    'contact.email': '> email:',
    'contact.line': 'say hi / features requests / feedback.',
    'status.default': '(c) 2026 musemesh',
    'toggle.invert': '[ invert ]',
    'aria.close': 'close window',
    'aria.pages': 'pages'
  },
  sr: {
    'titlebar': '❯ укључи публику',
    'wordmark': 'мјузмеш',
    'menu.home': 'ПОЧЕТНА',
    'menu.how': 'КАКО РАДИ',
    'menu.run': 'ПОКРЕНИ СОБУ',
    'menu.about': 'О ПРОЈЕКТУ',
    'menu.contact': 'КОНТАКТ',
    'home.tagline': 'сваки телефон у просторији постаје звучник',
    'home.line': 'без апликације. скенирај QR код, тапни једном и постајеш део перформанса.',
    'home.cta': '[ како ради ]',
    'how.h': 'КАКО РАДИ',
    'how.1': '> извођач покреће собу као сервер у свом DAW',
    'how.wifi': '> извођач и телефони морају бити на истој мрежи',
    'how.2': '> публика скенира QR код отварајући страницу у претраживачу',
    'how.3': '> сваки телефон пушта свој канал, синхронизовано',
    'how.4': '> просторија постаје озвучење',
    'how.lights': '> ускоро: просторија постаје и светлосни шоу — сваки телефон синхронизовано сценско светло, из MIDI клипова',
    'run.h': 'ПОКРЕНИ СОБУ',
    'run.1': '> учитај musemesh-server у свој DAW (VST3/AU)',
    'run.2': '> шаљи му канале преко musemesh-channel',
    'run.3': '> прикажи QR публици',
    'run.lights': '> ускоро: musemesh-light — телефони као синхронизована сценска светла',
    'run.dl': '[ преузми — бесплатно ]',
    'run.dlnote': 'macOS VST3/AU · ~30 MB · непотписана верзија — види INSTALL.txt унутра',
    'about.h': 'О ПРОЈЕКТУ',
    'about.text': 'мјузмеш је експеримент заједничког извођења: уместо једног разгласа, телефони публике постају дистрибуирани оркестар звучника. првобитно настао пре пет година, представљен је на ITP Camp 2021 са великим успехом. направили relja petrovic + ai.',
    'contact.h': 'КОНТАКТ',
    'contact.email': '> имејл:',
    'contact.line': 'јави се / предлози функција / утисци.',
    'status.default': '(c) 2026 мјузмеш',
    'toggle.invert': '[ обрни ]',
    'aria.close': 'затвори прозор',
    'aria.pages': 'странице'
  }
};
